# Generated by Django 5.0.6 on 2024-07-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification_devices",
            name="registration_id",
            field=models.TextField(max_length=1000),
        ),
    ]
