# Generated by Django 5.0.6 on 2024-07-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Generate_signals", "0004_brokers_alter_trade_history_result"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Brokers",
        ),
    ]
