# Generated by Django 5.0.7 on 2024-08-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Generate_signals", "0005_delete_brokers"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade_history",
            name="balance",
            field=models.BigIntegerField(default=0),
        ),
    ]
