# Generated by Django 5.0.7 on 2024-08-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Generate_signals", "0008_alter_trade_history_result_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade_history",
            name="balance",
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name="trade_history",
            name="type",
            field=models.CharField(
                choices=[("BUY", "BUY"), ("SELL", "SELL")], max_length=100
            ),
        ),
    ]
