# Generated by Django 5.0.4 on 2024-06-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals_auth', '0002_alter_mt5account_account_alter_mt5account_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mt5account',
            name='account',
            field=models.IntegerField(),
        ),
    ]
