# Generated by Django 5.0.4 on 2024-06-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals_auth', '0004_mt5account_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5account',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
