# Generated by Django 5.0.6 on 2024-07-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signals_auth", "0014_remove_user_fullname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verified",
            field=models.BooleanField(default=True),
        ),
    ]
