# Generated by Django 5.0.6 on 2024-07-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals_auth', '0019_mt5account_symbols_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mt5account_symbols',
            name='group_name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mt5account_symbols',
            name='type',
            field=models.CharField(blank=True, choices=[('currency', 'currency'), ('stocks', 'stocks'), ('cryptocurrency', 'cryptocurrency'), ('futures', 'futures'), ('metals', 'metals')], max_length=100, verbose_name='Trading Pair types'),
        ),
    ]
