# Generated by Django 5.0.7 on 2024-08-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signals_auth", "0021_remove_user_verified_user_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
