# Generated by Django 5.0.7 on 2024-08-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signals_auth", "0022_user_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="active",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
