# Generated by Django 5.0.7 on 2024-08-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signals_auth", "0025_devices"),
    ]

    operations = [
        migrations.AddField(
            model_name="devices",
            name="logged_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="devices",
            name="login_time",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="devices",
            name="logout_time",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
