# Generated by Django 5.0.7 on 2024-08-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("signals_auth", "0026_devices_logged_in_devices_login_time_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OneTimePassowrd",
            new_name="OneTimePassword",
        ),
    ]
