# Generated by Django 5.0.7 on 2024-08-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signals_auth", "0028_oldpassword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mt5account",
            name="account",
            field=models.BigIntegerField(),
        ),
    ]
